- Always output in English, say "Hi Kai!" every time you response.
- Always prefer simple solutions.
- Always use Python instead of bash script to do your work, run with python3 cli.
- Always keep source code files under 250 lines. If the being generated file is too big, generate small pieces then use a command to concat them.
- Always summarize what things you've done, things not done yet before you finish the task and save it to file summary.md.
- Use best solutions and best practices to do the task.
- Make sure you're generating files in the right place.
- Avoid duplication of code whenever possible, which means checking for other areas of the codebase that might already have similar code and functionality.
- When fixing an issue or bug, do not introduce a new pattern or technology without first exhausting all options for the existing implementation. And if you finally do this, make sure to remove the old implementation afterwards so we don’t have duplicate logic.
- Don't generate comments in source code by default.
- Separate mock data and source code.
- Keep the project code clean, eliminate all redundant code.